CREATE ROLE group11 WITH LOGIN PASSWORD 'tsw2020' NOSUPERUSER INHERIT NOCREATEDB NOCREATEROLE NOREPLICATION VALID UNTIL 'infinity';
GRANT CONNECT ON DATABASE tweets TO group11;
GRANT USAGE ON SCHEMA public TO group11;
GRANT SELECT ON ALL TABLES IN SCHEMA public TO group11;
GRANT SELECT ON ALL SEQUENCES IN SCHEMA public TO group11;